// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// createAlignmentMatrix
NumericMatrix createAlignmentMatrix(int nrow, int ncol);
RcppExport SEXP _wavematch_createAlignmentMatrix(SEXP nrowSEXP, SEXP ncolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type nrow(nrowSEXP);
    Rcpp::traits::input_parameter< int >::type ncol(ncolSEXP);
    rcpp_result_gen = Rcpp::wrap(createAlignmentMatrix(nrow, ncol));
    return rcpp_result_gen;
END_RCPP
}
// cpp_binned_coverage_bam
Rcpp::NumericVector cpp_binned_coverage_bam(const std::string& bam_path, const std::string& chrom, int chrom_length, int step_bp);
RcppExport SEXP _wavematch_cpp_binned_coverage_bam(SEXP bam_pathSEXP, SEXP chromSEXP, SEXP chrom_lengthSEXP, SEXP step_bpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type bam_path(bam_pathSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type chrom(chromSEXP);
    Rcpp::traits::input_parameter< int >::type chrom_length(chrom_lengthSEXP);
    Rcpp::traits::input_parameter< int >::type step_bp(step_bpSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_binned_coverage_bam(bam_path, chrom, chrom_length, step_bp));
    return rcpp_result_gen;
END_RCPP
}
// cpp_inferPairedEnd
bool cpp_inferPairedEnd(const std::string& bam_path, int maxReads);
RcppExport SEXP _wavematch_cpp_inferPairedEnd(SEXP bam_pathSEXP, SEXP maxReadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type bam_path(bam_pathSEXP);
    Rcpp::traits::input_parameter< int >::type maxReads(maxReadsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_inferPairedEnd(bam_path, maxReads));
    return rcpp_result_gen;
END_RCPP
}
// cpp_sample_block_maxima
NumericVector cpp_sample_block_maxima(const NumericVector& response, int half_window_bins, int nsamp, const LogicalVector& mask, double eps);
RcppExport SEXP _wavematch_cpp_sample_block_maxima(SEXP responseSEXP, SEXP half_window_binsSEXP, SEXP nsampSEXP, SEXP maskSEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type response(responseSEXP);
    Rcpp::traits::input_parameter< int >::type half_window_bins(half_window_binsSEXP);
    Rcpp::traits::input_parameter< int >::type nsamp(nsampSEXP);
    Rcpp::traits::input_parameter< const LogicalVector& >::type mask(maskSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_sample_block_maxima(response, half_window_bins, nsamp, mask, eps));
    return rcpp_result_gen;
END_RCPP
}
// cpp_relative_maxima
IntegerVector cpp_relative_maxima(const NumericVector& x, int order_bins, double eps);
RcppExport SEXP _wavematch_cpp_relative_maxima(SEXP xSEXP, SEXP order_binsSEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type order_bins(order_binsSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_relative_maxima(x, order_bins, eps));
    return rcpp_result_gen;
END_RCPP
}
// cpp_empirical_pvalues
NumericVector cpp_empirical_pvalues(const NumericVector& observed, const NumericVector& null_dist);
RcppExport SEXP _wavematch_cpp_empirical_pvalues(SEXP observedSEXP, SEXP null_distSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type observed(observedSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type null_dist(null_distSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_empirical_pvalues(observed, null_dist));
    return rcpp_result_gen;
END_RCPP
}
// cpp_expected_pvalues
NumericVector cpp_expected_pvalues(const NumericVector& observed, const NumericVector& null_dist);
RcppExport SEXP _wavematch_cpp_expected_pvalues(SEXP observedSEXP, SEXP null_distSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type observed(observedSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type null_dist(null_distSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_expected_pvalues(observed, null_dist));
    return rcpp_result_gen;
END_RCPP
}
// cpp_normalize_scores
IntegerVector cpp_normalize_scores(const NumericVector& scores);
RcppExport SEXP _wavematch_cpp_normalize_scores(SEXP scoresSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type scores(scoresSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_normalize_scores(scores));
    return rcpp_result_gen;
END_RCPP
}
// cpp_sample_null_distributions_batched
List cpp_sample_null_distributions_batched(const NumericVector& response, const IntegerVector& candidate_indices, int half_window_bins, int nsamp, const LogicalVector& null_mask_left, const LogicalVector& null_mask_right, int mid_point, bool use_split_halves, int min_null_size, double eps);
RcppExport SEXP _wavematch_cpp_sample_null_distributions_batched(SEXP responseSEXP, SEXP candidate_indicesSEXP, SEXP half_window_binsSEXP, SEXP nsampSEXP, SEXP null_mask_leftSEXP, SEXP null_mask_rightSEXP, SEXP mid_pointSEXP, SEXP use_split_halvesSEXP, SEXP min_null_sizeSEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type response(responseSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type candidate_indices(candidate_indicesSEXP);
    Rcpp::traits::input_parameter< int >::type half_window_bins(half_window_binsSEXP);
    Rcpp::traits::input_parameter< int >::type nsamp(nsampSEXP);
    Rcpp::traits::input_parameter< const LogicalVector& >::type null_mask_left(null_mask_leftSEXP);
    Rcpp::traits::input_parameter< const LogicalVector& >::type null_mask_right(null_mask_rightSEXP);
    Rcpp::traits::input_parameter< int >::type mid_point(mid_pointSEXP);
    Rcpp::traits::input_parameter< bool >::type use_split_halves(use_split_halvesSEXP);
    Rcpp::traits::input_parameter< int >::type min_null_size(min_null_sizeSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_sample_null_distributions_batched(response, candidate_indices, half_window_bins, nsamp, null_mask_left, null_mask_right, mid_point, use_split_halves, min_null_size, eps));
    return rcpp_result_gen;
END_RCPP
}
// cpp_sample_pooled_nulls_per_segment
List cpp_sample_pooled_nulls_per_segment(const NumericVector& response, const IntegerVector& segment_ids, int half_window_bins, int nsamp_per_segment, const IntegerVector& candidate_indices, const LogicalVector& null_mask, int min_null_size, double eps);
RcppExport SEXP _wavematch_cpp_sample_pooled_nulls_per_segment(SEXP responseSEXP, SEXP segment_idsSEXP, SEXP half_window_binsSEXP, SEXP nsamp_per_segmentSEXP, SEXP candidate_indicesSEXP, SEXP null_maskSEXP, SEXP min_null_sizeSEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type response(responseSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type segment_ids(segment_idsSEXP);
    Rcpp::traits::input_parameter< int >::type half_window_bins(half_window_binsSEXP);
    Rcpp::traits::input_parameter< int >::type nsamp_per_segment(nsamp_per_segmentSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type candidate_indices(candidate_indicesSEXP);
    Rcpp::traits::input_parameter< const LogicalVector& >::type null_mask(null_maskSEXP);
    Rcpp::traits::input_parameter< int >::type min_null_size(min_null_sizeSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_sample_pooled_nulls_per_segment(response, segment_ids, half_window_bins, nsamp_per_segment, candidate_indices, null_mask, min_null_size, eps));
    return rcpp_result_gen;
END_RCPP
}
// cpp_refine_adaptive_scales
List cpp_refine_adaptive_scales(const NumericVector& values, const IntegerVector& candidate_indices, const IntegerVector& initial_scales, const List& templates_per_scale, bool refine_neighbors, const NumericVector& intervals, double interval_bp);
RcppExport SEXP _wavematch_cpp_refine_adaptive_scales(SEXP valuesSEXP, SEXP candidate_indicesSEXP, SEXP initial_scalesSEXP, SEXP templates_per_scaleSEXP, SEXP refine_neighborsSEXP, SEXP intervalsSEXP, SEXP interval_bpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type values(valuesSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type candidate_indices(candidate_indicesSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type initial_scales(initial_scalesSEXP);
    Rcpp::traits::input_parameter< const List& >::type templates_per_scale(templates_per_scaleSEXP);
    Rcpp::traits::input_parameter< bool >::type refine_neighbors(refine_neighborsSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type intervals(intervalsSEXP);
    Rcpp::traits::input_parameter< double >::type interval_bp(interval_bpSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_refine_adaptive_scales(values, candidate_indices, initial_scales, templates_per_scale, refine_neighbors, intervals, interval_bp));
    return rcpp_result_gen;
END_RCPP
}
// cpp_compute_scale_energy
NumericMatrix cpp_compute_scale_energy(const NumericVector& values, const IntegerVector& centers, const List& templates_per_scale);
RcppExport SEXP _wavematch_cpp_compute_scale_energy(SEXP valuesSEXP, SEXP centersSEXP, SEXP templates_per_scaleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type values(valuesSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type centers(centersSEXP);
    Rcpp::traits::input_parameter< const List& >::type templates_per_scale(templates_per_scaleSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_compute_scale_energy(values, centers, templates_per_scale));
    return rcpp_result_gen;
END_RCPP
}
// cpp_find_point_sources
IntegerVector cpp_find_point_sources(const NumericVector& values, const IntegerVector& center_indices, const IntegerVector& span_bins);
RcppExport SEXP _wavematch_cpp_find_point_sources(SEXP valuesSEXP, SEXP center_indicesSEXP, SEXP span_binsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type values(valuesSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type center_indices(center_indicesSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type span_bins(span_binsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_find_point_sources(values, center_indices, span_bins));
    return rcpp_result_gen;
END_RCPP
}
// cpp_match_weights
NumericVector cpp_match_weights(const NumericVector& intervals, const NumericVector& weight_starts, const NumericVector& weight_ends, const NumericVector& weight_values, bool interpolate);
RcppExport SEXP _wavematch_cpp_match_weights(SEXP intervalsSEXP, SEXP weight_startsSEXP, SEXP weight_endsSEXP, SEXP weight_valuesSEXP, SEXP interpolateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type intervals(intervalsSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type weight_starts(weight_startsSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type weight_ends(weight_endsSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type weight_values(weight_valuesSEXP);
    Rcpp::traits::input_parameter< bool >::type interpolate(interpolateSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_match_weights(intervals, weight_starts, weight_ends, weight_values, interpolate));
    return rcpp_result_gen;
END_RCPP
}
// cpp_running_median
NumericVector cpp_running_median(const NumericVector& x, int window_size);
RcppExport SEXP _wavematch_cpp_running_median(SEXP xSEXP, SEXP window_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type window_size(window_sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_running_median(x, window_size));
    return rcpp_result_gen;
END_RCPP
}
// cpp_running_mean
NumericVector cpp_running_mean(const NumericVector& x, int window_size);
RcppExport SEXP _wavematch_cpp_running_mean(SEXP xSEXP, SEXP window_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type window_size(window_sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_running_mean(x, window_size));
    return rcpp_result_gen;
END_RCPP
}
// cpp_convolve_same
NumericVector cpp_convolve_same(const NumericVector& x, const NumericVector& kernel);
RcppExport SEXP _wavematch_cpp_convolve_same(SEXP xSEXP, SEXP kernelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type kernel(kernelSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_convolve_same(x, kernel));
    return rcpp_result_gen;
END_RCPP
}
// cpp_check_template_redundancy
LogicalVector cpp_check_template_redundancy(const IntegerVector& scale_map, const IntegerVector& scale_L_bins, const IntegerVector& fixed_templates, int n_total);
RcppExport SEXP _wavematch_cpp_check_template_redundancy(SEXP scale_mapSEXP, SEXP scale_L_binsSEXP, SEXP fixed_templatesSEXP, SEXP n_totalSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const IntegerVector& >::type scale_map(scale_mapSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type scale_L_bins(scale_L_binsSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type fixed_templates(fixed_templatesSEXP);
    Rcpp::traits::input_parameter< int >::type n_total(n_totalSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_check_template_redundancy(scale_map, scale_L_bins, fixed_templates, n_total));
    return rcpp_result_gen;
END_RCPP
}
// cpp_check_valley_between_peaks
List cpp_check_valley_between_peaks(double peak1_start, double peak1_end, double peak2_start, double peak2_end, double peak1_signal, double peak2_signal, const NumericVector& signal_values, const NumericVector& intervals, double null_median, double null_mad);
RcppExport SEXP _wavematch_cpp_check_valley_between_peaks(SEXP peak1_startSEXP, SEXP peak1_endSEXP, SEXP peak2_startSEXP, SEXP peak2_endSEXP, SEXP peak1_signalSEXP, SEXP peak2_signalSEXP, SEXP signal_valuesSEXP, SEXP intervalsSEXP, SEXP null_medianSEXP, SEXP null_madSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type peak1_start(peak1_startSEXP);
    Rcpp::traits::input_parameter< double >::type peak1_end(peak1_endSEXP);
    Rcpp::traits::input_parameter< double >::type peak2_start(peak2_startSEXP);
    Rcpp::traits::input_parameter< double >::type peak2_end(peak2_endSEXP);
    Rcpp::traits::input_parameter< double >::type peak1_signal(peak1_signalSEXP);
    Rcpp::traits::input_parameter< double >::type peak2_signal(peak2_signalSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type signal_values(signal_valuesSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type intervals(intervalsSEXP);
    Rcpp::traits::input_parameter< double >::type null_median(null_medianSEXP);
    Rcpp::traits::input_parameter< double >::type null_mad(null_madSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_check_valley_between_peaks(peak1_start, peak1_end, peak2_start, peak2_end, peak1_signal, peak2_signal, signal_values, intervals, null_median, null_mad));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_wavematch_createAlignmentMatrix", (DL_FUNC) &_wavematch_createAlignmentMatrix, 2},
    {"_wavematch_cpp_binned_coverage_bam", (DL_FUNC) &_wavematch_cpp_binned_coverage_bam, 4},
    {"_wavematch_cpp_inferPairedEnd", (DL_FUNC) &_wavematch_cpp_inferPairedEnd, 2},
    {"_wavematch_cpp_sample_block_maxima", (DL_FUNC) &_wavematch_cpp_sample_block_maxima, 5},
    {"_wavematch_cpp_relative_maxima", (DL_FUNC) &_wavematch_cpp_relative_maxima, 3},
    {"_wavematch_cpp_empirical_pvalues", (DL_FUNC) &_wavematch_cpp_empirical_pvalues, 2},
    {"_wavematch_cpp_expected_pvalues", (DL_FUNC) &_wavematch_cpp_expected_pvalues, 2},
    {"_wavematch_cpp_normalize_scores", (DL_FUNC) &_wavematch_cpp_normalize_scores, 1},
    {"_wavematch_cpp_sample_null_distributions_batched", (DL_FUNC) &_wavematch_cpp_sample_null_distributions_batched, 10},
    {"_wavematch_cpp_sample_pooled_nulls_per_segment", (DL_FUNC) &_wavematch_cpp_sample_pooled_nulls_per_segment, 8},
    {"_wavematch_cpp_refine_adaptive_scales", (DL_FUNC) &_wavematch_cpp_refine_adaptive_scales, 7},
    {"_wavematch_cpp_compute_scale_energy", (DL_FUNC) &_wavematch_cpp_compute_scale_energy, 3},
    {"_wavematch_cpp_find_point_sources", (DL_FUNC) &_wavematch_cpp_find_point_sources, 3},
    {"_wavematch_cpp_match_weights", (DL_FUNC) &_wavematch_cpp_match_weights, 5},
    {"_wavematch_cpp_running_median", (DL_FUNC) &_wavematch_cpp_running_median, 2},
    {"_wavematch_cpp_running_mean", (DL_FUNC) &_wavematch_cpp_running_mean, 2},
    {"_wavematch_cpp_convolve_same", (DL_FUNC) &_wavematch_cpp_convolve_same, 2},
    {"_wavematch_cpp_check_template_redundancy", (DL_FUNC) &_wavematch_cpp_check_template_redundancy, 4},
    {"_wavematch_cpp_check_valley_between_peaks", (DL_FUNC) &_wavematch_cpp_check_valley_between_peaks, 10},
    {NULL, NULL, 0}
};

RcppExport void R_init_wavematch(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
