# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

createAlignmentMatrix <- function(nrow, ncol) {
    .Call(`_wavematch_createAlignmentMatrix`, nrow, ncol)
}

cpp_binned_coverage_bam <- function(bam_path, chrom, chrom_length, step_bp) {
    .Call(`_wavematch_cpp_binned_coverage_bam`, bam_path, chrom, chrom_length, step_bp)
}

cpp_inferPairedEnd <- function(bam_path, maxReads = 10000L) {
    .Call(`_wavematch_cpp_inferPairedEnd`, bam_path, maxReads)
}

cpp_sample_block_maxima <- function(response, half_window_bins, nsamp, mask = logical(), eps = 1e-10) {
    .Call(`_wavematch_cpp_sample_block_maxima`, response, half_window_bins, nsamp, mask, eps)
}

cpp_relative_maxima <- function(x, order_bins, eps = 1e-10) {
    .Call(`_wavematch_cpp_relative_maxima`, x, order_bins, eps)
}

cpp_empirical_pvalues <- function(observed, null_dist) {
    .Call(`_wavematch_cpp_empirical_pvalues`, observed, null_dist)
}

cpp_expected_pvalues <- function(observed, null_dist) {
    .Call(`_wavematch_cpp_expected_pvalues`, observed, null_dist)
}

cpp_normalize_scores <- function(scores) {
    .Call(`_wavematch_cpp_normalize_scores`, scores)
}

cpp_sample_null_distributions_batched <- function(response, candidate_indices, half_window_bins, nsamp, null_mask_left = logical(), null_mask_right = logical(), mid_point = -1L, use_split_halves = FALSE, min_null_size = 25L, eps = 1e-10) {
    .Call(`_wavematch_cpp_sample_null_distributions_batched`, response, candidate_indices, half_window_bins, nsamp, null_mask_left, null_mask_right, mid_point, use_split_halves, min_null_size, eps)
}

cpp_sample_pooled_nulls_per_segment <- function(response, segment_ids, half_window_bins, nsamp_per_segment, candidate_indices = integer(), null_mask = logical(), min_null_size = 25L, eps = 1e-10) {
    .Call(`_wavematch_cpp_sample_pooled_nulls_per_segment`, response, segment_ids, half_window_bins, nsamp_per_segment, candidate_indices, null_mask, min_null_size, eps)
}

cpp_refine_adaptive_scales <- function(values, candidate_indices, initial_scales, templates_per_scale, refine_neighbors, intervals, interval_bp) {
    .Call(`_wavematch_cpp_refine_adaptive_scales`, values, candidate_indices, initial_scales, templates_per_scale, refine_neighbors, intervals, interval_bp)
}

cpp_compute_scale_energy <- function(values, centers, templates_per_scale) {
    .Call(`_wavematch_cpp_compute_scale_energy`, values, centers, templates_per_scale)
}

cpp_find_point_sources <- function(values, center_indices, span_bins) {
    .Call(`_wavematch_cpp_find_point_sources`, values, center_indices, span_bins)
}

cpp_match_weights <- function(intervals, weight_starts, weight_ends, weight_values, interpolate = FALSE) {
    .Call(`_wavematch_cpp_match_weights`, intervals, weight_starts, weight_ends, weight_values, interpolate)
}

cpp_running_median <- function(x, window_size) {
    .Call(`_wavematch_cpp_running_median`, x, window_size)
}

cpp_running_mean <- function(x, window_size) {
    .Call(`_wavematch_cpp_running_mean`, x, window_size)
}

cpp_convolve_same <- function(x, kernel) {
    .Call(`_wavematch_cpp_convolve_same`, x, kernel)
}

cpp_check_template_redundancy <- function(scale_map, scale_L_bins, fixed_templates, n_total) {
    .Call(`_wavematch_cpp_check_template_redundancy`, scale_map, scale_L_bins, fixed_templates, n_total)
}

cpp_check_valley_between_peaks <- function(peak1_start, peak1_end, peak2_start, peak2_end, peak1_signal, peak2_signal, signal_values, intervals, null_median = NA_real_, null_mad = NA_real_) {
    .Call(`_wavematch_cpp_check_valley_between_peaks`, peak1_start, peak1_end, peak2_start, peak2_end, peak1_signal, peak2_signal, signal_values, intervals, null_median, null_mad)
}

